#!usr/bin/env python3

# Created by: Dylan Hanna
# Created on: Sept 2019
# This is math program


def main():
    print("If a rectangle has the dimensions:")
    print("9cm x 12cm")
    print("")
    print("Area is {}".format(9*12))
    print("Perimeter is {}".format(2*(9+12))


if __name__ == "__main__":
    main()
